DROP DATABASE IF EXISTS PASTELERIA;
CREATE DATABASE PASTELERIA;
USE PASTELERIA;

-- TABLA USUARIOS --
CREATE TABLE USUARIOS (
    ID_USUARIOS BIGINT AUTO_INCREMENT NOT NULL,
    USUARIO VARCHAR(25) UNIQUE NOT NULL,
    CONTRASENA VARCHAR(25) NOT NULL,
    ROL ENUM('ADMIN', 'EMPLEADO', 'CLIENTE') NOT NULL,
    CONSTRAINT PRIMARY KEY (ID_USUARIOS)
);
-- TABLA DE CLIENTE --
	CREATE TABLE CLIENTE (
		ID_CLIENTE BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID DEL CLIENTE',
        USUARIO_ID BIGINT NOT NULL,
		NOMBRE VARCHAR(20) NOT NULL COMMENT 'NOMBRE DEL CLIENTE',
		APELLIDOS VARCHAR(45) NOT NULL COMMENT 'APELLIDOS DEL CLIENTE',
		CORREO VARCHAR(50) NOT NULL COMMENT 'CORREO ELECTRONICO',
		NUM_TLF INT NOT NULL COMMENT 'NUMERO DE TELEFONO',
		CONSTRAINT PRIMARY KEY (ID_CLIENTE),
        CONSTRAINT FK_CLIENTE_USUARIO 
            FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID_USUARIOS)
	);

-- TABLA DE PRODUCTO --
	CREATE TABLE PRODUCTO (
		ID_PRODUCTO BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID DEL PRODUCTO',
        NOMBRE VARCHAR(25) NOT NULL COMMENT 'NOMBRE DEL PRODUCTO',
        PRECIO DECIMAL(10,2) NOT NULL COMMENT 'PRECIO DEL PRODUCTO',
        DESCRIPCION VARCHAR(150) NULL COMMENT 'INFORMACION EXTRA SOBRE EL PRODUCTO',
        IMAGEN VARCHAR(200) COMMENT 'URL O NOMBRE DEL ARCHIVO DE IMAGEN',
        TIPO ENUM('PANADERIA','PASTELERIA') NOT NULL,
		CONSTRAINT PRIMARY KEY (ID_PRODUCTO)
    );

-- TABLA DE PEDIDO -- 
	CREATE TABLE PEDIDO (
		ID_PEDIDO BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID DEL PEDIDO',
		CLIENTE_ID BIGINT NOT NULL COMMENT 'ID DEL CLIENTE QUE HACE EL PEDIDO',
        FECHA_PEDIDO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'FECHA DE CUANDO SE REALIZA EL PEDIDO',
        FECHA_ENTREGA DATETIME NOT NULL COMMENT 'FECHA DE ENTREGA DEL PEDIDO',
        ESTADO ENUM ('PENDIENTE','ENTREGADO') NOT NULL DEFAULT 'PENDIENTE' COMMENT 'ESTADO DEL PEDIDO',
        TOTAL DECIMAL(10,2) NOT NULL COMMENT 'TOTAL A PAGAR POR EL CLIENTE',
        CONSTRAINT PRIMARY KEY (ID_PEDIDO),
        CONSTRAINT FK_PEDIDO_CLIENTE
            FOREIGN KEY (CLIENTE_ID) REFERENCES CLIENTE(ID_CLIENTE)
	);

    CREATE TABLE PEDIDO_PRODUCTO (
        ID_PP BIGINT AUTO_INCREMENT NOT NULL,
        PEDIDO_ID BIGINT NOT NULL,
        PRODUCTO_ID BIGINT NOT NULL,
        CANTIDAD INT NOT NULL,
        CONSTRAINT PRIMARY KEY (ID_PP),
        CONSTRAINT FK_PP_PEDIDO 
            FOREIGN KEY (PEDIDO_ID) REFERENCES PEDIDO(ID_PEDIDO),
        CONSTRAINT FK_PP_PRODUCTO 
            FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTO(ID_PRODUCTO)
    );

-- TABLA INGREDIENTE --
	CREATE TABLE INGREDIENTE (
		ID_INGREDIENTE BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID DEL INGREDIENTE',
        NOMBRE VARCHAR(20) NOT NULL COMMENT 'NOMBRE DEL INGREDIENTE',
        STOCK INT NOT NULL COMMENT 'STOCK DE CADA INGREDIENTE',
        ALERGENOS ENUM (
            'GLUTEN', 'CRUSTACEOS', 'HUEVOS', 'PESCADO', 'CACAHUETES', 'SOJA', 'LECHE',
            'FRUTOS_CASCARA', 'APIO', 'MOSTAZA', 'SESAMO', 'SULFITOS', 'ALTRAMUCES', 'MOLUSCOS'
        ) NOT NULL,
        CONSTRAINT PRIMARY KEY (ID_INGREDIENTE)
    );
    
-- TABLA INGREDIENTES DE LOS PRODUCTOS -- 
	CREATE TABLE INGREDIENTE_PRODUCTO (
		ID_IP BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID DE LA TABLA',
        PRODUCTO_ID BIGINT NOT NULL COMMENT 'ID DEL PRODUCTO',
        INGREDIENTE_ID BIGINT NOT NULL COMMENT 'ID DEL INGREDIENTE',
        CONSTRAINT PRIMARY KEY (ID_IP),
        CONSTRAINT FK_IP_PRODUCTO
            FOREIGN KEY (PRODUCTO_ID) REFERENCES PRODUCTO(ID_PRODUCTO),
        CONSTRAINT FK_IP_INGREDIENTE
            FOREIGN KEY (INGREDIENTE_ID) REFERENCES INGREDIENTE(ID_INGREDIENTE)
    );
    
-- EMPLEADOS Y JORNADAS -- 

-- EMPLEADO -- 
	CREATE TABLE EMPLEADO (
        ID_EMPLEADO BIGINT AUTO_INCREMENT NOT NULL,
		USUARIO_ID BIGINT NOT NULL, 
        NOMBRE VARCHAR(20) NOT NULL COMMENT 'NOMBRE DEL USUARIO',
        APELLIDOS VARCHAR(45) NOT NULL COMMENT 'APELLIDOS DEL USUARIO',
        ES_ADMIN BOOLEAN,
        CONSTRAINT PRIMARY KEY (ID_EMPLEADO),
        CONSTRAINT FK_EMPLEADO_USUARIO
            FOREIGN KEY (USUARIO_ID) REFERENCES USUARIOS(ID_USUARIOS)
    );
    
-- JORNADA --
	CREATE TABLE JORNADA (
		ID_JORNADA BIGINT NOT NULL AUTO_INCREMENT COMMENT 'ID DE LA JORNADA',
        EMPLEADO_ID BIGINT NOT NULL COMMENT 'EMPLEADO QUE FICHA',
        FECHA DATE NOT NULL COMMENT 'DIA DE FICHAJE',
        HORA_INICIO TIME NOT NULL COMMENT 'HORA DE INICIO',
        HORA_SALIDA TIME NULL COMMENT 'HORA DE SALIDA',
        HORAS_DIA DECIMAL(4,2) NULL COMMENT 'HORAS DIARIAS',
        CONSTRAINT PRIMARY KEY (ID_JORNADA),
        CONSTRAINT FK_JORNADA_EMPLEADO 
            FOREIGN KEY (EMPLEADO_ID) REFERENCES EMPLEADO(ID_EMPLEADO)
    );

INSERT INTO USUARIOS (USUARIO, CONTRASENA, ROL) VALUES ('admin', 'admin', 'ADMIN');
INSERT INTO EMPLEADO (USUARIO_ID, NOMBRE, APELLIDOS, ES_ADMIN)
VALUES (1, 'Admin', 'Sistema', TRUE);

INSERT INTO INGREDIENTE (NOMBRE, STOCK, ALERGENOS) VALUES
('Harina', 100, 'GLUTEN'),
('Azúcar', 80, 'GLUTEN'),
('Huevo', 60, 'HUEVOS'),
('Leche', 50, 'LECHE'),
('Chocolate', 40, 'LECHE');

INSERT INTO PRODUCTO (NOMBRE, PRECIO, DESCRIPCION, IMAGEN) VALUES
('Barra de Pan', 1.20, 'Pan tradicional recién horneado', 'barra_pan.jpg'),
('Croissant', 1.80, 'Croissant de mantequilla', 'croissant.jpg'),
('Bizcocho Casero', 6.50, 'Bizcocho esponjoso casero', 'bizcocho.jpg'),
('Tarta Chocolate Deluxe', 20.00, 'Tarta de chocolate con cobertura', 'tarta_chocolate_deluxe.jpg');


INSERT INTO INGREDIENTE_PRODUCTO (PRODUCTO_ID, INGREDIENTE_ID)
SELECT p.ID_PRODUCTO, i.ID_INGREDIENTE
FROM PRODUCTO p, INGREDIENTE i
WHERE p.NOMBRE = 'Barra de Pan'
  AND i.NOMBRE = 'Harina';

INSERT INTO INGREDIENTE_PRODUCTO (PRODUCTO_ID, INGREDIENTE_ID)
SELECT p.ID_PRODUCTO, i.ID_INGREDIENTE
FROM PRODUCTO p, INGREDIENTE i
WHERE p.NOMBRE = 'Croissant'
  AND i.NOMBRE IN ('Harina', 'Huevo', 'Leche');

INSERT INTO INGREDIENTE_PRODUCTO (PRODUCTO_ID, INGREDIENTE_ID)
SELECT p.ID_PRODUCTO, i.ID_INGREDIENTE
FROM PRODUCTO p, INGREDIENTE i
WHERE p.NOMBRE = 'Bizcocho Casero'
  AND i.NOMBRE IN ('Harina', 'Azúcar', 'Huevo', 'Leche');

INSERT INTO INGREDIENTE_PRODUCTO (PRODUCTO_ID, INGREDIENTE_ID)
SELECT p.ID_PRODUCTO, i.ID_INGREDIENTE
FROM PRODUCTO p, INGREDIENTE i
WHERE p.NOMBRE = 'Tarta Chocolate Deluxe'
  AND i.NOMBRE IN ('Harina', 'Azúcar', 'Huevo', 'Leche', 'Chocolate');

UPDATE PRODUCTO SET TIPO = 'PANADERIA'
WHERE NOMBRE IN ('Barra de Pan', 'Croissant');

UPDATE PRODUCTO SET TIPO = 'PASTELERIA'
WHERE NOMBRE IN ('Bizcocho Casero', 'Tarta Chocolate Deluxe', 'Tarta Chocolate', 'Tarta Fresa');


  
